"""Константы героев Dota 2 — актуальный патч (февраль 2026)."""

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class HeroData:
    """Данные одного героя."""

    hero_id: int
    name_en: str
    name_ru: str


# Полный список героев Dota 2 (hero_id соответствует API OpenDota / Stratz).
# ID с пропусками — особенность нумерации Valve.
HEROES: tuple[HeroData, ...] = (
    HeroData(1, "Anti-Mage", "Анти-Маг"),
    HeroData(2, "Axe", "Акс"),
    HeroData(3, "Bane", "Бэйн"),
    HeroData(4, "Bloodseeker", "Бладсикер"),
    HeroData(5, "Crystal Maiden", "Кристал Мэйден"),
    HeroData(6, "Drow Ranger", "Дроу Рейнджер"),
    HeroData(7, "Earthshaker", "Ёршейкер"),
    HeroData(8, "Juggernaut", "Джаггернаут"),
    HeroData(9, "Mirana", "Мирана"),
    HeroData(10, "Morphling", "Морфлинг"),
    HeroData(11, "Shadow Fiend", "Шэдоу Финд"),
    HeroData(12, "Phantom Lancer", "Фантом Лансер"),
    HeroData(13, "Puck", "Пак"),
    HeroData(14, "Pudge", "Пудж"),
    HeroData(15, "Razor", "Рейзор"),
    HeroData(16, "Sand King", "Сэнд Кинг"),
    HeroData(17, "Storm Spirit", "Шторм Спирит"),
    HeroData(18, "Sven", "Свен"),
    HeroData(19, "Tiny", "Тайни"),
    HeroData(20, "Vengeful Spirit", "Венга"),
    HeroData(21, "Windranger", "Виндрейнджер"),
    HeroData(22, "Zeus", "Зевс"),
    HeroData(23, "Kunkka", "Кунка"),
    HeroData(25, "Lina", "Лина"),
    HeroData(26, "Lion", "Лайон"),
    HeroData(27, "Shadow Shaman", "Шэдоу Шаман"),
    HeroData(28, "Slardar", "Слардар"),
    HeroData(29, "Tidehunter", "Тайдхантер"),
    HeroData(30, "Witch Doctor", "Витч Доктор"),
    HeroData(31, "Lich", "Лич"),
    HeroData(32, "Riki", "Рики"),
    HeroData(33, "Enigma", "Энигма"),
    HeroData(34, "Tinker", "Тинкер"),
    HeroData(35, "Sniper", "Снайпер"),
    HeroData(36, "Necrophos", "Некрофос"),
    HeroData(37, "Warlock", "Варлок"),
    HeroData(38, "Beastmaster", "Бистмастер"),
    HeroData(39, "Queen of Pain", "Квопа"),
    HeroData(40, "Venomancer", "Веномансер"),
    HeroData(41, "Faceless Void", "Войд"),
    HeroData(42, "Wraith King", "Рейс Кинг"),
    HeroData(43, "Death Prophet", "Дезпро"),
    HeroData(44, "Phantom Assassin", "Фантом Ассассин"),
    HeroData(45, "Pugna", "Пугна"),
    HeroData(46, "Templar Assassin", "Темплар Ассассин"),
    HeroData(47, "Viper", "Вайпер"),
    HeroData(48, "Luna", "Луна"),
    HeroData(49, "Dragon Knight", "Драгон Найт"),
    HeroData(50, "Dazzle", "Даззл"),
    HeroData(51, "Clockwerk", "Клокверк"),
    HeroData(52, "Leshrac", "Лешрак"),
    HeroData(53, "Nature's Prophet", "Фурион"),
    HeroData(54, "Lifestealer", "Лайфстилер"),
    HeroData(55, "Dark Seer", "Дарк Сир"),
    HeroData(56, "Clinkz", "Клинкз"),
    HeroData(57, "Omniknight", "Омникнайт"),
    HeroData(58, "Enchantress", "Энчантресс"),
    HeroData(59, "Huskar", "Хускар"),
    HeroData(60, "Night Stalker", "Найт Сталкер"),
    HeroData(61, "Broodmother", "Бруда"),
    HeroData(62, "Bounty Hunter", "Баунти Хантер"),
    HeroData(63, "Weaver", "Вивер"),
    HeroData(64, "Jakiro", "Джакиро"),
    HeroData(65, "Batrider", "Бэтрайдер"),
    HeroData(66, "Chen", "Чен"),
    HeroData(67, "Spectre", "Спектра"),
    HeroData(68, "Ancient Apparition", "Аппарат"),
    HeroData(69, "Doom", "Дум"),
    HeroData(70, "Ursa", "Урса"),
    HeroData(71, "Spirit Breaker", "Спирит Брейкер"),
    HeroData(72, "Gyrocopter", "Гирокоптер"),
    HeroData(73, "Alchemist", "Алхимик"),
    HeroData(74, "Invoker", "Инвокер"),
    HeroData(75, "Silencer", "Сайленсер"),
    HeroData(76, "Outworld Destroyer", "ОД"),
    HeroData(77, "Lycan", "Ликан"),
    HeroData(78, "Brewmaster", "Брюмастер"),
    HeroData(79, "Shadow Demon", "Шэдоу Демон"),
    HeroData(80, "Lone Druid", "Лон Друид"),
    HeroData(81, "Chaos Knight", "Хаос Найт"),
    HeroData(82, "Meepo", "Мипо"),
    HeroData(83, "Treant Protector", "Тренант Протектор"),
    HeroData(84, "Ogre Magi", "Огр Маги"),
    HeroData(85, "Undying", "Андаинг"),
    HeroData(86, "Rubick", "Рубик"),
    HeroData(87, "Disruptor", "Дизраптор"),
    HeroData(88, "Nyx Assassin", "Никс Ассассин"),
    HeroData(89, "Naga Siren", "Нага Сирена"),
    HeroData(90, "Keeper of the Light", "Котл"),
    HeroData(91, "Io", "Ио"),
    HeroData(92, "Visage", "Визаж"),
    HeroData(93, "Slark", "Сларк"),
    HeroData(94, "Medusa", "Медуза"),
    HeroData(95, "Troll Warlord", "Тролль"),
    HeroData(96, "Centaur Warrunner", "Кентавр"),
    HeroData(97, "Magnus", "Магнус"),
    HeroData(98, "Timbersaw", "Тимбер"),
    HeroData(99, "Bristleback", "Бристлбэк"),
    HeroData(100, "Tusk", "Таск"),
    HeroData(101, "Skywrath Mage", "Скаймаг"),
    HeroData(102, "Abaddon", "Абаддон"),
    HeroData(103, "Elder Titan", "Элдер Титан"),
    HeroData(104, "Legion Commander", "Легион Коммандер"),
    HeroData(105, "Techies", "Течис"),
    HeroData(106, "Ember Spirit", "Эмбер Спирит"),
    HeroData(107, "Earth Spirit", "Ёрс Спирит"),
    HeroData(108, "Underlord", "Андерлорд"),
    HeroData(109, "Terrorblade", "Террорблейд"),
    HeroData(110, "Phoenix", "Феникс"),
    HeroData(111, "Oracle", "Оракл"),
    HeroData(112, "Winter Wyvern", "Винтер Виверн"),
    HeroData(113, "Arc Warden", "Арк Варден"),
    HeroData(114, "Monkey King", "Манки Кинг"),
    HeroData(119, "Dark Willow", "Дарк Виллоу"),
    HeroData(120, "Pangolier", "Панголир"),
    HeroData(121, "Grimstroke", "Гримстроук"),
    HeroData(123, "Hoodwink", "Худвинк"),
    HeroData(126, "Void Spirit", "Войд Спирит"),
    HeroData(128, "Snapfire", "Снапфайр"),
    HeroData(129, "Mars", "Марс"),
    HeroData(131, "Ringmaster", "Рингмастер"),
    HeroData(135, "Dawnbreaker", "Донбрейкер"),
    HeroData(136, "Marci", "Марси"),
    HeroData(137, "Primal Beast", "Праймал Бист"),
    HeroData(138, "Muerta", "Муэрта"),
    HeroData(145, "Kez", "Кез"),
    HeroData(155, "Largo", "Ларго"),
)

# Быстрый доступ по hero_id
HERO_BY_ID: dict[int, HeroData] = {h.hero_id: h for h in HEROES}

TOTAL_HEROES = len(HEROES)
