"""Маппинг предметов Dota 2: item_id → имя EN/RU."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ItemData:
    """Данные одного предмета."""

    item_id: int
    name_en: str
    name_ru: str


# Полный список предметов Dota 2 (item_id соответствует API Stratz / OpenDota).
# Включает основные предметы, используемые в билдах.
ITEMS: tuple[ItemData, ...] = (
    # --- Расходники / Стартовые ---
    ItemData(38, "Clarity", "Ясность"),
    ItemData(39, "Faerie Fire", "Волшебный огонь"),
    ItemData(40, "Smoke of Deceit", "Дым обмана"),
    ItemData(42, "Observer Ward", "Обсервер вард"),
    ItemData(43, "Sentry Ward", "Сентри вард"),
    ItemData(44, "Tango", "Танго"),
    ItemData(45, "Animal Courier", "Курьер"),
    ItemData(46, "Flying Courier", "Летающий курьер"),
    ItemData(216, "Dust of Appearance", "Пыль проявления"),
    ItemData(218, "Iron Branch", "Веточка"),
    ItemData(237, "Healing Salve", "Лечебная мазь"),
    ItemData(241, "Mango", "Манго"),
    ItemData(265, "Infused Raindrops", "Зачарованные капли"),
    ItemData(593, "Blood Grenade", "Кровавая граната"),
    # --- Базовые предметы ---
    ItemData(16, "Gauntlets of Strength", "Латные рукавицы"),
    ItemData(17, "Slippers of Agility", "Туфли ловкости"),
    ItemData(18, "Mantle of Intelligence", "Мантия разума"),
    ItemData(19, "Circlet", "Обруч"),
    ItemData(20, "Belt of Strength", "Пояс силы"),
    ItemData(21, "Band of Elvenskin", "Эльфийская кожа"),
    ItemData(22, "Robe of the Magi", "Мантия мага"),
    ItemData(23, "Ogre Axe", "Топор огра"),
    ItemData(24, "Blade of Alacrity", "Клинок проворства"),
    ItemData(25, "Staff of Wizardry", "Посох волшебства"),
    ItemData(27, "Ring of Health", "Кольцо здоровья"),
    ItemData(29, "Claymore", "Клеймор"),
    ItemData(30, "Javelin", "Дротик"),
    ItemData(34, "Magic Stick", "Волшебная палочка"),
    ItemData(36, "Magic Wand", "Волшебная жезл"),
    ItemData(37, "Ghost Scepter", "Призрачный скипетр"),
    ItemData(48, "Stout Shield", "Крепкий щит"),
    ItemData(56, "Quelling Blade", "Топор рубки"),
    ItemData(73, "Blight Stone", "Камень порчи"),
    ItemData(77, "Wind Lace", "Кружево ветра"),
    ItemData(181, "Orb of Venom", "Сфера яда"),
    ItemData(240, "Crown", "Корона"),
    ItemData(569, "Orb of Corrosion", "Сфера коррозии"),
    ItemData(600, "Cornucopia", "Рог изобилия"),
    # --- Ботинки ---
    ItemData(29, "Boots of Speed", "Сапоги скорости"),
    ItemData(50, "Phase Boots", "Фазовые сапоги"),
    ItemData(63, "Power Treads", "Силовые нити"),
    ItemData(79, "Arcane Boots", "Тайные сапоги"),
    ItemData(180, "Boots of Travel", "Сапоги путешественника"),
    ItemData(214, "Tranquil Boots", "Сапоги спокойствия"),
    ItemData(931, "Boots of Bearing", "Сапоги стойкости"),
    # --- Основные предметы ---
    ItemData(1, "Blink Dagger", "Кинжал мерцания"),
    ItemData(102, "Overwhelming Blink", "Превосходящее мерцание"),
    ItemData(103, "Swift Blink", "Стремительное мерцание"),
    ItemData(104, "Arcane Blink", "Тайное мерцание"),
    ItemData(2, "Blades of Attack", "Клинки атаки"),
    ItemData(4, "Chainmail", "Кольчуга"),
    ItemData(5, "Broadsword", "Палаш"),
    ItemData(6, "Quarterstaff", "Посох"),
    ItemData(7, "Platemail", "Латы"),
    ItemData(8, "Helm of Iron Will", "Шлем железной воли"),
    ItemData(10, "Ring of Protection", "Кольцо защиты"),
    ItemData(11, "Ring of Regen", "Кольцо регенерации"),
    ItemData(12, "Gloves of Haste", "Перчатки спешки"),
    ItemData(13, "Mithril Hammer", "Мифриловый молот"),
    ItemData(14, "Demon Edge", "Демонический клинок"),
    ItemData(15, "Cloak", "Плащ"),
    ItemData(26, "Point Booster", "Прибавка к характеристикам"),
    ItemData(31, "Morbid Mask", "Маска смерти"),
    ItemData(32, "Sacred Relic", "Священная реликвия"),
    ItemData(33, "Hyperstone", "Гиперстоун"),
    ItemData(35, "Gem of True Sight", "Самоцвет истинного зрения"),
    ItemData(41, "Tome of Knowledge", "Книга знаний"),
    ItemData(47, "Bottle", "Бутылка"),
    ItemData(51, "Oblivion Staff", "Посох забвения"),
    ItemData(55, "Perseverance", "Упорство"),
    ItemData(57, "Ring of Basilius", "Кольцо Базилиуса"),
    ItemData(60, "Void Stone", "Камень пустоты"),
    ItemData(61, "Mystic Staff", "Мистический посох"),
    ItemData(65, "Ultimate Orb", "Сфера могущества"),
    ItemData(67, "Reaver", "Жнец"),
    ItemData(69, "Eagle Song", "Песнь орла"),
    ItemData(71, "Soul Ring", "Кольцо души"),
    ItemData(75, "Urn of Shadows", "Урна теней"),
    # --- Средние предметы ---
    ItemData(50, "Phase Boots", "Фазовые сапоги"),
    ItemData(36, "Magic Wand", "Волшебная палочка"),
    ItemData(73, "Blight Stone", "Камень порчи"),
    ItemData(75, "Urn of Shadows", "Урна теней"),
    ItemData(79, "Arcane Boots", "Тайные сапоги"),
    ItemData(86, "Hand of Midas", "Рука Мидаса"),
    ItemData(88, "Shadow Blade", "Теневой клинок"),
    ItemData(90, "Drum of Endurance", "Барабан стойкости"),
    ItemData(92, "Vanguard", "Авангард"),
    ItemData(94, "Blade Mail", "Клинковая кольчуга"),
    ItemData(96, "Soul Booster", "Прибавка к душе"),
    ItemData(98, "Hood of Defiance", "Капюшон стойкости"),
    ItemData(100, "Mekansm", "Меканизм"),
    ItemData(102, "Overwhelming Blink", "Превосходящее мерцание"),
    ItemData(108, "Eul's Scepter of Divinity", "Скипетр Эвла"),
    ItemData(110, "Force Staff", "Посох силы"),
    ItemData(112, "Dagon 1", "Дагон 1"),
    ItemData(116, "Necronomicon 1", "Некрономикон 1"),
    ItemData(119, "Vladmir's Offering", "Дар Владмира"),
    ItemData(121, "Buckler", "Баклер"),
    ItemData(123, "Medallion of Courage", "Медальон мужества"),
    ItemData(125, "Pipe of Insight", "Трубка прозрения"),
    ItemData(127, "Atos", "Атос"),
    ItemData(131, "Armlet of Mordiggian", "Наручник Мордиггиана"),
    ItemData(133, "Orchid Malevolence", "Орхидея злобы"),
    ItemData(135, "Crystalys", "Кристалис"),
    ItemData(137, "Shadow Amulet", "Теневой амулет"),
    ItemData(139, "Glimmer Cape", "Мерцающая накидка"),
    ItemData(145, "Aether Lens", "Линза эфира"),
    ItemData(147, "Dragon Lance", "Драконье копьё"),
    ItemData(149, "Meteor Hammer", "Метеоритный молот"),
    ItemData(151, "Nullifier", "Нейтрализатор"),
    ItemData(152, "Aeon Disk", "Диск вечности"),
    ItemData(154, "Spirit Vessel", "Сосуд духа"),
    ItemData(156, "Holy Locket", "Священный локет"),
    ItemData(158, "Kaya", "Кая"),
    ItemData(160, "Yasha and Kaya", "Яша и Кая"),
    ItemData(162, "Kaya and Sange", "Кая и Санге"),
    ItemData(164, "Witch Blade", "Клинок ведьмы"),
    ItemData(168, "Falcon Blade", "Клинок сокола"),
    ItemData(569, "Orb of Corrosion", "Сфера коррозии"),
    ItemData(571, "Mage Slayer", "Убийца магов"),
    ItemData(573, "Fluffy Hat", "Пушистая шляпа"),
    # --- Крупные предметы ---
    ItemData(48, "Stout Shield", "Крепкий щит"),
    ItemData(141, "Black King Bar", "Посох Чёрного Короля"),
    ItemData(143, "Sange and Yasha", "Санге и Яша"),
    ItemData(147, "Dragon Lance", "Драконье копьё"),
    ItemData(149, "Meteor Hammer", "Метеоритный молот"),
    ItemData(151, "Nullifier", "Нейтрализатор"),
    ItemData(152, "Aeon Disk", "Диск вечности"),
    ItemData(154, "Spirit Vessel", "Сосуд духа"),
    ItemData(156, "Holy Locket", "Священный локет"),
    ItemData(158, "Kaya", "Кая"),
    ItemData(160, "Yasha and Kaya", "Яша и Кая"),
    ItemData(162, "Kaya and Sange", "Кая и Санге"),
    ItemData(164, "Witch Blade", "Клинок ведьмы"),
    ItemData(170, "Aghanim's Shard", "Осколок Аганима"),
    ItemData(172, "Sange", "Санге"),
    ItemData(174, "Yasha", "Яша"),
    ItemData(176, "Manta Style", "Мантия стиля"),
    ItemData(178, "Diffusal Blade", "Клинок рассеивания"),
    ItemData(180, "Boots of Travel", "Сапоги путешественника"),
    ItemData(185, "Daedalus", "Дедал"),
    ItemData(187, "Monkey King Bar", "Посох Царя Обезьян"),
    ItemData(190, "Battle Fury", "Боевое безумие"),
    ItemData(193, "Ethereal Blade", "Эфирный клинок"),
    ItemData(194, "Radiance", "Сияние"),
    ItemData(196, "Butterfly", "Бабочка"),
    ItemData(201, "Assault Cuirass", "Штурмовая кираса"),
    ItemData(202, "Heart of Tarrasque", "Сердце Тарраска"),
    ItemData(203, "Shiva's Guard", "Защита Шивы"),
    ItemData(204, "Bloodstone", "Камень крови"),
    ItemData(206, "Linken's Sphere", "Сфера Линкена"),
    ItemData(208, "Sphere", "Сфера"),
    ItemData(210, "Satanic", "Сатаник"),
    ItemData(212, "Eye of Skadi", "Око Скади"),
    ItemData(220, "Refresher Orb", "Сфера обновления"),
    ItemData(223, "Desolator", "Опустошитель"),
    ItemData(225, "Mjollnir", "Мьёлльнир"),
    ItemData(226, "Maelstrom", "Мальстрём"),
    ItemData(229, "Divine Rapier", "Божественная рапира"),
    ItemData(231, "Abyssal Blade", "Клинок бездны"),
    ItemData(232, "Skull Basher", "Черепобой"),
    ItemData(235, "Hurricane Pike", "Ураганная пика"),
    ItemData(236, "Aghanim's Scepter", "Скипетр Аганима"),
    ItemData(242, "Silver Edge", "Серебряный клинок"),
    ItemData(244, "Lotus Orb", "Сфера Лотоса"),
    ItemData(247, "Solar Crest", "Солнечный гребень"),
    ItemData(249, "Guardian Greaves", "Гвардейские поножи"),
    ItemData(250, "Octarine Core", "Октариновое ядро"),
    ItemData(252, "Bloodthorn", "Кровошип"),
    ItemData(254, "Echo Sabre", "Эхо-сабля"),
    ItemData(256, "Crimson Guard", "Багровая гвардия"),
    ItemData(259, "Helm of the Dominator", "Шлем доминатора"),
    ItemData(263, "Mask of Madness", "Маска безумия"),
    ItemData(267, "Tome of Knowledge", "Книга знаний"),
    ItemData(269, "Helm of the Overlord", "Шлем повелителя"),
    ItemData(271, "Holy Locket", "Священный локет"),
    ItemData(273, "Voodoo Mask", "Маска вуду"),
    ItemData(277, "Wraith Band", "Повязка призрака"),
    ItemData(534, "Bracer", "Браслет"),
    ItemData(569, "Orb of Corrosion", "Сфера коррозии"),
    ItemData(571, "Mage Slayer", "Убийца магов"),
    ItemData(573, "Fluffy Hat", "Пушистая шляпа"),
    ItemData(574, "Falcon Blade", "Клинок сокола"),
    ItemData(577, "Witch Blade", "Клинок ведьмы"),
    ItemData(578, "Glepnir", "Глейпнир"),
    ItemData(585, "Eternal Shroud", "Вечный саван"),
    ItemData(596, "Overwhelming Blink", "Превосходящее мерцание"),
    ItemData(597, "Swift Blink", "Стремительное мерцание"),
    ItemData(598, "Arcane Blink", "Тайное мерцание"),
    ItemData(600, "Cornucopia", "Рог изобилия"),
    ItemData(603, "Wind Waker", "Вихревик"),
    ItemData(604, "Wraith Pact", "Пакт призрака"),
    ItemData(609, "Pavise", "Павиза"),
    ItemData(610, "Revenant's Brooch", "Брошь ревенанта"),
    ItemData(612, "Phylactery", "Филактерия"),
    ItemData(635, "Disperser", "Рассеиватель"),
    ItemData(638, "Parasma", "Парасма"),
    ItemData(675, "Khanda", "Кханда"),
    ItemData(676, "Harpoon", "Гарпун"),
    ItemData(680, "Null Talisman", "Нулевой талисман"),
    # --- Нейтральные предметы ---
    ItemData(287, "Trusty Shovel", "Верная лопата"),
    ItemData(288, "Arcane Ring", "Тайное кольцо"),
    ItemData(290, "Broom Handle", "Ручка метлы"),
    ItemData(291, "Pig Pole", "Свинячий шест"),
    ItemData(292, "Ironwood Tree", "Железное дерево"),
    ItemData(294, "Fairy's Trinket", "Безделушка феи"),
    ItemData(297, "Possessed Mask", "Одержимая маска"),
    ItemData(300, "Dragon Scale", "Чешуя дракона"),
    ItemData(301, "Essence Ring", "Кольцо сущности"),
    ItemData(304, "Grove Bow", "Лук рощи"),
    ItemData(306, "Vambrace", "Наруч"),
    ItemData(309, "Philosopher's Stone", "Философский камень"),
    ItemData(312, "Spider Legs", "Лапы паука"),
    ItemData(313, "Enchanted Quiver", "Зачарованный колчан"),
    ItemData(326, "Elven Tunic", "Эльфийская туника"),
    ItemData(327, "Cloak of Flames", "Плащ пламени"),
    ItemData(331, "Timeless Relic", "Безвременная реликвия"),
    ItemData(335, "Spell Prism", "Призма заклинаний"),
    ItemData(336, "Pirate Hat", "Пиратская шляпа"),
    ItemData(354, "Apex", "Апекс"),
    ItemData(355, "Book of the Dead", "Книга мёртвых"),
    ItemData(356, "Fallen Sky", "Падающее небо"),
    ItemData(357, "Ex Machina", "Экс Махина"),
    ItemData(358, "Mirror Shield", "Зеркальный щит"),
    ItemData(359, "Giant's Ring", "Кольцо великана"),
    ItemData(362, "Stormcrafter", "Штормовик"),
    ItemData(366, "Seeds of Serenity", "Семена безмятежности"),
    ItemData(370, "Lance of Pursuit", "Копьё преследования"),
    ItemData(371, "Occult Bracelet", "Оккультный браслет"),
    ItemData(372, "Tome of Aghanim", "Книга Аганима"),
    ItemData(374, "Craggy Coat", "Каменная шкура"),
    ItemData(375, "Whisper of the Dread", "Шёпот ужаса"),
    ItemData(376, "Blighted Spirit", "Заражённый дух"),
    ItemData(377, "Light Collector", "Собиратель света"),
    ItemData(379, "Eye of the Vizier", "Глаз визиря"),
    ItemData(381, "Rattlecage", "Трескуч"),
    ItemData(565, "Specialist's Array", "Набор специалиста"),
    ItemData(638, "Parasma", "Парасма"),
)

# --- Индекс для быстрого поиска ---

ITEM_BY_ID: dict[int, ItemData] = {}
for _item in ITEMS:
    if _item.item_id not in ITEM_BY_ID:
        ITEM_BY_ID[_item.item_id] = _item


def get_item_name_en(item_id: int) -> str:
    """Получить английское имя предмета по ID. Возвращает 'Item #ID' если не найден."""
    item = ITEM_BY_ID.get(item_id)
    return item.name_en if item else f"Item #{item_id}"


def get_item_name_ru(item_id: int) -> str:
    """Получить русское имя предмета по ID. Возвращает 'Предмет #ID' если не найден."""
    item = ITEM_BY_ID.get(item_id)
    return item.name_ru if item else f"Предмет #{item_id}"
